# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will* override
# any settings specified in this file.

# JVM arguments for Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Use Java 17 for Gradle builds
org.gradle.java.home=/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home

# AndroidX package structure
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Enable non-transitive R classes
android.nonTransitiveRClass=true